dist: trusty
sudo: false
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cppcheck
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - CONFIG=Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cppcheck
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - CONFIG=Debug

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cppcheck
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CONFIG=Release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cppcheck
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CONFIG=Debug

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake -DCHECK_BOUND:BOOL=TRUE ./test 
  - scan-build cmake --build . --config ${CONFIG} -- -j2
  - ./fixed_test
