dist: trusty
sudo: false
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cppcheck
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cppcheck
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"    

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake ./test
  - cmake --build . -- -j2
  - ./Debug/*
  - cppcheck --quiet --error-exitcode=1