dist: trusty
sudo: false
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cppcheck
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cppcheck
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  
    env:
      - CONFIG=Release
    env:
      - CONFIG=Debug

before_install:
    - eval "${MATRIX_EVAL}"
    - eval "${BUILD_CONFIG}"

script:
  - cmake ./test
  - scan-build cmake --build . --config Debug -- -j2
  - ./fixed_test
  - rm -r CMakeFiles/fixed_test.dir/*.o
  - rm fixed_test
  - echo ${CONFIG}
  - scan-build cmake --build . --config Release -- -j2
  - cppcheck --quiet --error-exitcode=1 -f -I include/ ./test/*.cpp
